GET {{webApiHostAddress}}/api/todo-items
Accept: application/json

### Create new user
# @name createUser
POST {{webApiHostAddress}}/api/users
Content-Type: application/json

{
  "userName": "{{$random.name.username}}",
  "email": "{{$random.email}}"
}

> {%
client.global.set("{{userId}}", response.body.id)
%}

### Get user by id (using the stored variable)
GET {{webApiHostAddress}}/api/users/{{userId}}
Content-Type: application/json
